### ISSUE TITLE
Vanilla World Height Limit Still Enforced on First Login

### ISSUE THREAD

**Issue by ghost** [hohserg1/DimensionalLayers#6]
**Modpack**
List of mods which required for reproduce bug:

- Cubic Chunks
- CubicGen
- DimensionalLayers

**World customization preset**
Any arrangement of dimensions where blocks end up above y=256

**Describe the bug**
Attempting to break or place blocks above the vanilla height limit will lead to the vanilla height limit message displaying, and blocks not properly registering as broken and/or placed. Ghosting occurs, and eventually a client crash (it says disconnected from server, then boots you to the multiplayer world selection menu even though the world was singleplayer)

**Steps to reproduce the behavior**
1. Make a world with the listed mods
2. Go above y=256 and try to place blocks and destroy blocks
3. See the bug
4. Save & Exit, then reload world; bug is gone.

**Expected behavior**
Blocks work normally.

**Screenshots**
![2024-10-01_15 56 40](https://github.com/user-attachments/assets/6a939ad1-d585-4e56-9b8e-aa979fcc72c7)

**Comment by hohserg1** [comment]
Woah! Thank you for report! However its Cubic Chunks issue
**Modpack**

- Cubic Chunks
- CubicWorldGen

**Steps to reproduce the behavior**

same

But I cant find out relevant issue at CC repo, huh

**Comment by hohserg1** [comment]
About this bug written on CC curseforge page
![image-5](https://github.com/user-attachments/assets/5e28fc85-dd71-42ca-9be2-d2fc3d82df6b)
