### ISSUE TITLE
Weird assertion error

### ISSUE THREAD

**Issue by MCTian-mi** [hohserg1/DimensionalLayers#7]
**Modpack**
[Supersymmetry](https://www.curseforge.com/minecraft/modpacks/supersymmetry), with vintagefix removed
**World customization preset**
N/A
**Describe the bug**
The game crashes during finalization
[crash](https://mclo.gs/EZ5VIFV)

**Steps to reproduce the behavior**
1. Adding CC & DL to the pack and remove the vintagefix.
2. Start the game
3. Game crashes during finalization

**Expected behavior**
Game runs

**Screenshots**
N/A

**Comment by hohserg1** [comment]
Thank you for report! 
Will be fixed in next update

**Comment by MCTian-mi** [comment]
seems to be fixed alr?

**Comment by hohserg1** [comment]
ah, sorry, I forgot to mark it as resolved
